service: source-as-a-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  source:
    handler: handler.source
    timeout: 30
    events:
      - http:
          path: source
          method: get